version: '3.8'
services: 
  mongodb:
    image: mongo
    restart: always 
    volumes: 
      - my_data:/data/db 
  nodejs:
    build: 
      context: ./nodejs/
      dockerfile: Dockerfile
    depends_on: 
      - mongodb
    volumes: 
      - ./nodejs:/app
    ports: 
      - "5000:5000"
    entrypoint: ["node", "app.js"]
  
volumes: 
  my_data: 
